"""Baseline migration

Revision ID: 4c4b896275eb
Revises: 
Create Date: 2026-06-28 01:12:47.356296

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c4b896275eb'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'subtotal',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('orders', 'tax_amount',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('orders', 'discount_amount',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False,
               existing_server_default=sa.text('0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'discount_amount',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('orders', 'tax_amount',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('orders', 'subtotal',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True,
               existing_server_default=sa.text('0'))
    # ### end Alembic commands ###
